Repository openpredictionmarkets/socialpredict, pull requests merged in 2024-08, with the labels that each got.

#238 Add Createmarket unit tests
  backend/handlers/markets/createmarket.go
  backend/handlers/markets/createmarket_test.go
Labels: enhancement, go

#243 Documentation for Testing
  README/TESTING/TESTING_README.md
  README/TESTING/stress_testing/docker_stats.csv
  README/TESTING/stress_testing/docker_usage_to_csv
Labels: documentation

#241 feat: added a 'CLOSED' message to markets that are no longer live
  frontend/src/components/tables/MarketTables.jsx
Labels: enhancement

#235 Feature/404 page
  frontend/src/App.jsx
  frontend/src/helpers/AppRoutes.jsx
  frontend/src/pages/notfound/NotFound.jsx
Labels: enhancement

#242 Frontend refactoring
  frontend/src/App.jsx
  frontend/src/components/charts/MarketChart.jsx
  frontend/src/components/inputs/InputBox.jsx
  frontend/src/components/loaders/LoadingSpinner.jsx
  frontend/src/components/marketDetails/MarketDetailsLayout.jsx
  frontend/src/components/modals/login/LoginModalClick.jsx
  frontend/src/components/resolutions/ResolutionAlert.jsx
  frontend/src/components/sidebar/Sidebar.jsx
  frontend/src/components/tables/MarketTables.jsx
  frontend/src/components/tables/MobileMarketCard.jsx
  frontend/src/helpers/formatResolutionDate.js
  frontend/src/hooks/useMarketDetails.jsx
  frontend/src/hooks/usePortfolio.jsx
  frontend/src/hooks/useUserData.jsx
  frontend/src/pages/about/About.jsx
  frontend/src/pages/create/Create.jsx
  frontend/src/pages/home/Home.jsx
  frontend/src/pages/marketDetails/MarketDetails.jsx
  frontend/src/pages/profile/Profile.jsx
  frontend/src/pages/style/Style.jsx
Labels: enhancement

#250 Move GetNumMarketUsers from listusers to models/bets
  backend/handlers/markets/listmarkets.go
  backend/handlers/markets/marketdetailshandler.go
  backend/handlers/users/listusers.go
  backend/models/bets.go
  backend/models/bets_test.go
Labels: go

#264 Backend and Frontend Additions to Percolate User Credit Into Sidebar
  backend/handlers/users/usercredit.go
  backend/server/server.go
  frontend/src/components/sidebar/Sidebar.jsx
  frontend/src/components/utils/userFinanceTools/FetchUserCredit.jsx
Labels: enhancement, go, react

#274 Creating setuphandler to allow in-game set up to be queried via API
  README/TESTING/TESTING_README.md
  backend/handlers/setup/setuphandler.go
  backend/handlers/setup/setuphandler_test.go
  backend/server/server.go
Labels: enhancement
