Repository openpredictionmarkets/socialpredict, pull requests merged in 2025-04, with the labels that each got.

#388 Variety of Documents Describing Our Prediction Market Math Graphically
  README/MATH/Positions_Calculations.xlsx
  README/MATH/Prediction_Market_Math.pdf
  README/MATH/Prediction_Market_Math.tex
Labels: documentation

#421 Dependabot go modules update
  backend/go.mod
  backend/go.sum
Labels: dependencies

#423 Changing env_writer_dev.sh and docker-compose-dev.yaml to allow running on new versions os MacOS
  README/LOCAL_SETUP.md
  SocialPredict
  scripts/dev/env_writer_dev.sh
  scripts/docker-compose-dev.yaml
Labels: bug
